const Map<String, String> zhTW = {
  'appTitle': '我的應用',
  'settings': '設定',
  'themeMode': '主題模式',
  'light': '淺色',
  'dark': '深色',
  'system': '系統預設',
  'navigationPaneDisplayMode': '導航窗格顯示模式',
  'navigationIndicator': '導航指示器',
  'accentColor': '強調色',
  'textDirection': '文字方向',
  'leftToRight': '由左至右',
  'rightToLeft': '由右至左',
  'locale': '語言',
  'newTab': '新增分頁',
  'closeTab': '關閉分頁',
  'back': '上一頁',
  'forward': '下一頁',
  'refresh': '重新整理',
  'home': '首頁',
  'news': '新聞',
  'weather': '天氣',
};
