const Map<String, String> ko = {
  'appTitle': '내 앱',
  'settings': '설정',
  'themeMode': '테마 모드',
  'light': '라이트',
  'dark': '다크',
  'system': '시스템 기본값',
  'navigationPaneDisplayMode': '탐색 창 표시 모드',
  'navigationIndicator': '탐색 표시기',
  'accentColor': '강조 색상',
  'textDirection': '텍스트 방향',
  'leftToRight': '왼쪽에서 오른쪽으로',
  'rightToLeft': '오른쪽에서 왼쪽으로',
  'locale': '언어',
  'newTab': '새 탭',
  'closeTab': '탭 닫기',
  'back': '뒤로',
  'forward': '앞으로',
  'refresh': '새로 고침',
  'home': '홈',
  'news': '뉴스',
  'weather': '날씨',
  'sticky': '스티키',
  'end': '엔드',
  'workspaceNameLabel': '작업 공간 이름',
  'workspaceUrlLabel': '작업 공간 URL',
  'newWorkspace': '새 작업 공간',
  'add': '추가',
  'cancel': '취소',
};
