const Map<String, String> en = {
  'appTitle': 'My App',
  'settings': 'Settings',
  'themeMode': 'Theme Mode',
  'light': 'Light',
  'dark': 'Dark',
  'system': 'System',
  'navigationPaneDisplayMode': 'Navigation Pane Display Mode',
  'navigationIndicator': 'Navigation Indicator',
  'accentColor': 'Accent Color',
  'textDirection': 'Text Direction',
  'leftToRight': 'Left to Right',
  'rightToLeft': 'Right to Left',
  'locale': 'Language',
  'newTab': 'New Tab',
  'closeTab': 'Close Tab',
  'back': 'Back',
  'forward': 'Forward',
  'refresh': 'Refresh',
  'home': 'Home',
  'news': 'News',
  'weather': 'Weather',
  'sticky': 'Sticky',
  'end': 'End',
  'workspaceNameLabel': 'Workspace Name',
  'workspaceUrlLabel': 'Workspace URL',
  'newWorkspace': 'New Workspace',
  'add': 'Add',
  'cancel': 'Cancel',
};
